mysite/food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    #/food/
    path('', views.index, name='index'),
    path('item/', views.item, name='item'),

    path('<int:item_id>', views.detail, name='detail'),
    #add items
    path('add', views.create_item, name='create_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
]

mysite/food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name

    item_name = models.CharField(max_length=200) # max_length is mandatory for charfield
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://www.fnasafety.com/wp-content/uploads/2016/04/ComingSoon2-fnasafety.png")

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
#from django.template import loader
# Create your views here.

def index(request):
    item_list = Item.objects.all()
    #template = loader.get_template('food/index.html')

    context = {
        'item_list': item_list,
    }

    #return HttpResponse(template.render(context, request))
    return render(request,'food/index.html',context)

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }

    return render(request, 'food/detail.html', context)

def create_item(request):

    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form})

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
     <nav class="navbar navbar-black bg-dark" >
        <a href="#" class="navbar-brand"> FoodApp </a>

        <div class="navbar">
            <a class="nav-item nav-link" href="{% url 'food:create_item' %}"> Add Item</a>
            <a class="nav-item nav-link" href="#"> Delete Item</a>
            <a class="nav-item nav-link" href="#"> View Item</a>
        </div>
    </nav>
    {% block body %}

    {% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ item.item_image }}" class="card" height="300px"/>
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>${{ item.item_price }}</h3>
        </div>
    </div>

</div>


{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title> Food index View</title>
</head>
<body>
    {% block body %}

    {% for item in item_list %}
    <div class="row">
        <div class="col-md-3 offset-md-2" >
            <img class="card" height="100%" width="100%" object-fit="cover" src="{{ item.item_image }}"/>
        </div>
        <div class="col-md-4">
            <h3> {{ item.item_name }} </h3>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>


    {% endfor %}

    {% endblock %}
</body>
</html>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit"> Save </button>
</form>
{% endblock %}